#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X


# no hace falta cambiar el gap si estas en 1080, te recomiendo que lo dejes en 12
bspc config window_gap         12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

picom &


feh --bg-fill /home/zoso/Desktop/wallpapers/wp1.png &


~/.config/polybar/launch.sh &


# configurar el border de las ventanas activas
bspc config border_width 0

